name: "Vprofile IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  aws_regiomn: us-east-1
  EKS_CLUSTER_NAME: vprofile-cluster

jobs:
  terraform:
    name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
          # -backend-config="region=${{ env.aws_regiomn }}" \
          # -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        # working-directory: ./terraform
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true
      
      - name: Terraform plan status
        if: steps.plan.outcome == 'failure' 
        run: exit 1     


      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   working-directory: ./terraform
      #   run: terraform apply -auto-approve